name: CI Pipeline Batik App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code with Submodules
        uses: actions/checkout@v4
        with:
          # PENTING: Perintah ini memaksa GitHub mengunduh seluruh isi source code di dalam submodule
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 1. Build & Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./cms-catalog-backend # Disesuaikan dengan nama folder di gambar
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/company-batik-backend:latest

      # 2. Build & Push Frontend (Next.js)
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./company-profile-batik # Disesuaikan dengan nama folder di gambar
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/company-batik-frontend:latest

      # 3. Build & Push CMS Dashboard (React)
      - name: Build and Push CMS
        uses: docker/build-push-action@v5
        with:
          context: ./dashboard-cms # Disesuaikan dengan nama folder di gambar
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/company-batik-cms:latest

      - name: Trigger Jenkins Deployment
        if: success()
        run: |
          echo "Menghubungi Jenkins untuk me-refresh semua service Batik App..."
          curl -X POST "${{ secrets.JENKINS_URL }}/job/deploy-batik-app/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}&TARGET_SERVICES=all"